name: 3d_tracking
channels:
  - rapidsai
  - conda-forge
  - menpo
dependencies:
  - python=3.12
  - numpy=2.2.6
  - matplotlib
  - pandas
  - pip
  - black
  - glew
  - mesalib
  - mesa-libgl-cos6-x86_64
  - glfw3
  - ipykernel
  - ffmpeg
  - rapids=25.12
  - cuda-version>=12.2,<=12.9
  - scikit-learn
  - jax
  - pip
  - pip:
      - hydra-core
      - h5py
      - natsort
      - nvidia-ml-py3
      - tqdm
      - psutil
      - mediapy
      - imageio[ffmpeg]
      - ray[core]
      - mujoco
      - mujoco-mjx
      - ipywidgets
      - uv
variables:             # Set MuJoCo environment variables
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl