name: 3d_tracking
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - pandas
  - pip
  - black
  - glew
  - mesalib
  - glfw
  - ipykernel
  - ffmpeg
  - pip
  - pip:
      - hydra-core
      - jax
      - h5py
      - natsort
      - tqdm
      - psutil
      - mediapy
      - imageio[ffmpeg]
      - ray[core]
      - mujoco
      - mujoco-mjx
      - ipywidgets
      - uv