# @package _global_.dataset

defaults:
  - preprocessing
  - postprocessing

name: courtship
env_name: courtship
version: Data_analysis
train: True


concat:
  input_pattern: 'postprocessing/ik_output_${anatomy.name}_${dataset.name}.h5'
  output_file: 'ik_output_combined_${anatomy.name}_${dataset.name}.h5'
  enable_jax: True