# @package _global_.dataset

defaults:
  - preprocessing
  - postprocessing

name: free_walking
env_name: free_walking
version: Data_analysis
train: True

concat:
  input_pattern: 'ik_output_${anatomy.name}_${dataset.name}.h5'
  output_file: 'ik_output_combined_${anatomy.name}_${dataset.name}.h5'
  enable_jax: True