# @package _global_.dataset

defaults:
  - preprocessing
  - postprocessing

name: free_walking
env_name: free_walking
version: Predictions_3D_20260114-145343
train: True

concat:
  input_pattern: 'ik_output_${anatomy.name}.h5'
  output_file: 'ik_output_combined.h5'
  enable_jax: True